#! /bin/bash
#PBS -l nodes=4:ppn=44
#PBS -l walltime=00:10:00
#PBS -V
#PBS -j oe
#PBS -N minighost
cd $PBS_O_WORKDIR


export OMP_NUM_THREADS=2

EXE=${PWD}/source/miniGhost.x

aprun -n 72 -N 18 -S 9 -d 2 ${EXE} --npx 4 --npy 6 --npz 3 --scaling 1 --nx 672 --ny 672 --nz 672 --num_vars 40 --num_spikes 1 --debug_grid 1 --report_diffusion 21 --percent_sum 100 --num_tsteps 20 --stencil 24 --comm_method 12 --report_perf 1 --error_tol 8
